theme: jekyll-theme-minimal

title: Nicolás Harari

description: Bachelor graduate in economics at University of Buenos Aires. First year Master in Economics student at Torcuato di Tella University.

logo: "/images/git.jpg"
