theme: jekyll-theme-minimal
title: Curriculum Vitae
description: Second year Master in Economics student at Torcuato di Tella University. Bachelor graduate in Economics at University of Buenos Aires. 

logo: "/images/pic.png"
