theme: jekyll-theme-minimal
title: 
description: First year Master in Economics student at Torcuato di Tella University. Bachelor graduate in Economics at University of Buenos Aires. 

logo: "/images/pic.png"
