theme: jekyll-theme-minimal
title: Curriculum Vitae
description: First year Economics Ph.D. student at Boston University. Master in Economics student at Torcuato di Tella University (thesis pending) and bachelor graduate in Economics at University of Buenos Aires. 
logo: "/images/pic.png"
